#!/bin/sh

rm *.class

javac RegexValidator.java -cp ".:/usr/share/java/junit.jar"
javac DomainValidator.java -cp ".:/usr/share/java/junit.jar" -sourcepath "." 
javac InetAddressValidator.java -cp ".:/usr/share/java/junit.jar" -sourcepath "."
javac ResultPair.java -cp ".:/usr/share/java/junit.jar" -sourcepath "."
javac UrlValidator.java -cp ".:/usr/share/java/junit.jar" -sourcepath "."

javac UrlValidatorTest.java -cp ".:/usr/share/java/junit.jar" -sourcepath "."
javac Main.java -cp ".:/usr/share/java/junit.jar" -sourcepath "."

java Main -cp ".:/usr/share/java/junit.jar"
